name: catit_app
description: Catit - Mindful Household Management
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.0.0
  hive_flutter: ^1.1.0
  uuid: ^4.4.0
  intl: ^0.20.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
